### ISSUE TITLE
More specific date detection for PIN

### ISSUE THREAD

**Issue by kober32** [wultra/passphrase-meter#11]
Right now, pin check returns `POSSIBLY_DATE` flag. This flag is covering both dates and years.

1. This should be split into `YEAR` and `DATE`
2. There should be a configuration for what kind of date format to support (array of strings possibly or pre-defined sets). Right now mmdd, ddmm and more are possible at the same time even if that doesn't make sense in some regions.

**Comment by petrdvorak** [comment]
Through the time test, it seems this is not really required.
