### ISSUE TITLE
Freeze on Android if test pin of one digit

### ISSUE THREAD

**Issue by JulienNevo** [wultra/passphrase-meter#21]
On Android (SDK 29), using v1.0.0, checking a pin of 1 digit provokes a unlimited freeze:

To test:
`PasswordTester.getInstance().testPin("0")`

Regards.

**Comment by petrdvorak** [comment]
@JulienNevo Thank you for the report - we will have a look.

**Comment by kober32** [comment]
Hi @JulienNevo. Thanks for the report. I fixed the issue and release it for both iOS and Android under the version `1.0.1`.
