### ISSUE TITLE
After pod update, it gives me "No such module `PasswordMeter`" issue

### ISSUE THREAD

**Issue by Mehul18292** [wultra/passphrase-meter#27]
It was working perfectly fine.

But once after pod get updated, no any version updated for this. But it started giving me this error: No such module "PasswordMeter"

I tried deleting deriveddata as well as cleaning the build. But still it didnt worked. Any workaround please.

**Comment by kober32** [comment]
Hello @Mehul18292, can you provide as much data from your environment as possible? Especially your Cocoapods version and Xcode version. 

There were no significant changes regarding integration. Did you try to clear Cocoapods cache in `~/Library/Caches/CocoaPods/`?

Also, did your `pod update` upgraded your Passphrase Meter version from `1.0.0` to `1.0.1`? If not, it's not gonna be a library issue...

**Comment by Mehul18292** [comment]
Thanks @kober32 for your prompt response. I figured out the issue. It happened due to some changes in build configuration done by me. There was no any issue from your code. Closing this issue as it was not issue related to your repo.
