### ISSUE TITLE
Remove binary data from repository

### ISSUE THREAD

**Issue by hvge** [wultra/passphrase-meter#5]
Currently, we have precomputed dictionaries for CZSK & EN languages stored in the git repository. We should remove those files and move such data preparation to a `pod-install` or `gradle build` tasks.

**Comment by hvge** [comment]
Just for note, I have prepared tooling that allows us to upload such data as a part of library release. Check [scripts in cc7](https://github.com/wultra/cc7/blob/develop/openssl-build/build-publish.sh#L116).

**Comment by kober32** [comment]
I'm closing this. It's too much work to support it on multiple platforms (Windows, Linux, macOS) on multiple systems (Android and iOS), and multiple dependency managers (maven, cocoapods, SPM).
